name: VirtualBosses
main: dev.darkhorizon.es.virtualbosses.Main
version: "1.0"
depend: [ProtocolLib, Vault]
softdepend: [HolographicDisplays]
commands:
  blackmarket:
    usage: /<command>
    aliases: [bmarket, blackm, traficante]
  virtualboss:
    usage: /<command>
    aliases: [vboss, virtualb, vb, boss]