name: VirtualBosses
main: dev.darkhorizon.es.black.Main
version: "1.0"
load: POSTWORLD
commands:
  blackmarket:
    usage: /<command>
    aliases: [bmarket, blackm, traficante]
  virtualboss:
    usage: /<command>
    aliases: [vboss, virtualb, vb, boss]